# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meng.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MengT(object):
    def setupUi(self, MengT):
        MengT.setObjectName("MengT")
        MengT.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(MengT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tb_view = QtWidgets.QTextBrowser(MengT)
        self.tb_view.setObjectName("tb_view")
        self.verticalLayout.addWidget(self.tb_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_count = QtWidgets.QLineEdit(MengT)
        self.le_count.setObjectName("le_count")
        self.horizontalLayout.addWidget(self.le_count)
        self.pushButton = QtWidgets.QPushButton(MengT)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MengT)
        QtCore.QMetaObject.connectSlotsByName(MengT)

    def retranslateUi(self, MengT):
        _translate = QtCore.QCoreApplication.translate
        MengT.setWindowTitle(_translate("MengT", "随机蒙题"))
        self.pushButton.setText(_translate("MengT", "生成"))
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'meng.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLineEdit, QPushButton,
    QSizePolicy, QTextBrowser, QVBoxLayout, QWidget)

class Ui_MengT(object):
    def setupUi(self, MengT):
        if not MengT.objectName():
            MengT.setObjectName(u"MengT")
        MengT.resize(400, 300)
        self.verticalLayout = QVBoxLayout(MengT)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tb_view = QTextBrowser(MengT)
        self.tb_view.setObjectName(u"tb_view")

        self.verticalLayout.addWidget(self.tb_view)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.le_count = QLineEdit(MengT)
        self.le_count.setObjectName(u"le_count")

        self.horizontalLayout.addWidget(self.le_count)

        self.pushButton = QPushButton(MengT)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout.addWidget(self.pushButton)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(MengT)

        QMetaObject.connectSlotsByName(MengT)
    # setupUi

    def retranslateUi(self, MengT):
        MengT.setWindowTitle(QCoreApplication.translate("MengT", u"\u968f\u673a\u8499\u9898", None))
        self.pushButton.setText(QCoreApplication.translate("MengT", u"\u751f\u6210", None))
    # retranslateUi

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'meng.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLineEdit, QPushButton,
    QSizePolicy, QTextBrowser, QVBoxLayout, QWidget)

class Ui_MengT(object):
    def setupUi(self, MengT):
        if not MengT.objectName():
            MengT.setObjectName(u"MengT")
        MengT.resize(400, 300)
        self.verticalLayout = QVBoxLayout(MengT)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tb_view = QTextBrowser(MengT)
        self.tb_view.setObjectName(u"tb_view")

        self.verticalLayout.addWidget(self.tb_view)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.le_count = QLineEdit(MengT)
        self.le_count.setObjectName(u"le_count")

        self.horizontalLayout.addWidget(self.le_count)

        self.pushButton = QPushButton(MengT)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout.addWidget(self.pushButton)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(MengT)

        QMetaObject.connectSlotsByName(MengT)
    # setupUi

    def retranslateUi(self, MengT):
        MengT.setWindowTitle(QCoreApplication.translate("MengT", u"\u968f\u673a\u8499\u9898", None))
        self.pushButton.setText(QCoreApplication.translate("MengT", u"\u751f\u6210", None))
    # retranslateUi

